# Generated by Django 3.2 on 2021-04-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
